/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Symptom } from "./Symptom";
import { SymptomCountArgs } from "./SymptomCountArgs";
import { SymptomFindManyArgs } from "./SymptomFindManyArgs";
import { SymptomFindUniqueArgs } from "./SymptomFindUniqueArgs";
import { DeleteSymptomArgs } from "./DeleteSymptomArgs";
import { SymptomService } from "../symptom.service";
@graphql.Resolver(() => Symptom)
export class SymptomResolverBase {
  constructor(protected readonly service: SymptomService) {}

  async _symptomsMeta(
    @graphql.Args() args: SymptomCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Symptom])
  async symptoms(
    @graphql.Args() args: SymptomFindManyArgs
  ): Promise<Symptom[]> {
    return this.service.symptoms(args);
  }

  @graphql.Query(() => Symptom, { nullable: true })
  async symptom(
    @graphql.Args() args: SymptomFindUniqueArgs
  ): Promise<Symptom | null> {
    const result = await this.service.symptom(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Symptom)
  async deleteSymptom(
    @graphql.Args() args: DeleteSymptomArgs
  ): Promise<Symptom | null> {
    try {
      return await this.service.deleteSymptom(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
