/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Diagnosis } from "./Diagnosis";
import { DiagnosisCountArgs } from "./DiagnosisCountArgs";
import { DiagnosisFindManyArgs } from "./DiagnosisFindManyArgs";
import { DiagnosisFindUniqueArgs } from "./DiagnosisFindUniqueArgs";
import { DeleteDiagnosisArgs } from "./DeleteDiagnosisArgs";
import { DiagnosisService } from "../diagnosis.service";
@graphql.Resolver(() => Diagnosis)
export class DiagnosisResolverBase {
  constructor(protected readonly service: DiagnosisService) {}

  async _diagnosesMeta(
    @graphql.Args() args: DiagnosisCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Diagnosis])
  async diagnoses(
    @graphql.Args() args: DiagnosisFindManyArgs
  ): Promise<Diagnosis[]> {
    return this.service.diagnoses(args);
  }

  @graphql.Query(() => Diagnosis, { nullable: true })
  async diagnosis(
    @graphql.Args() args: DiagnosisFindUniqueArgs
  ): Promise<Diagnosis | null> {
    const result = await this.service.diagnosis(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Diagnosis)
  async deleteDiagnosis(
    @graphql.Args() args: DeleteDiagnosisArgs
  ): Promise<Diagnosis | null> {
    try {
      return await this.service.deleteDiagnosis(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
